[package]
name = "nsq"
version = "0.1.0"
edition = "2018"


[[bin]]
name = "consumer"
path = "src/consumer.rs"

[[bin]]
name = "producer"
path = "src/producer.rs"

[dependencies]
tokio-nsq = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
signal-hook = "*"
